title: "Shadhini Jayatilake"

permalink: pretty

markdown_ext: markdown,mkdown,mkdn,mkd,md

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  auto_id_prefix: "id-"
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  gfm_quirks:
    - no_auto_typographic
    - paragraph_end

collections:
  projects:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
